vich_uploader:
    db_driver: orm


    mappings:
        product_image:
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/photos'
           

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
